services:
  cassandra:
    ports:
      - "127.0.0.1:9042:9042"
    environment:
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_PASSWORD_SEEDER: "yes"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vpn_network

  vpn-backend:
    ports:
      - "8080:8080"
    image: vodev1405/traveler_vpn_backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/prod/Dockerfile
    pull_policy: missing
    command: ["java", "-XX:+UseG1GC", "-Xmx512m", "-jar", "app.jar"]
    user: 100:1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vpn_network
  
  vault:
    ports:
      - "127.0.0.1:8200:8200"
    user: 100:1000
    networks:
      - vpn_network

  vault-agent:
    user: 100:1000
    networks:
      - vpn_network

networks:
  vpn_network:
    driver: bridge