services:
  cassandra:
    image: cassandra:5.0
    environment:
      CASSANDRA_CLUSTER_NAME: VpnCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_PASSWORD_SEEDER: "yes"
      DOTENV_PRIVATE_KEY: ${DOTENV_PRIVATE_KEY}
    command: ["/bin/sh", "-c", "init.sh & docker-entrypoint.sh cassandra -f"]
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always
    secrets:
      - cassandra_secrets
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./docker/cassandra/init.sh:/usr/local/bin/init.sh

  vpn-backend:
    environment:
      FLYWAY_NATIVE_CONNECTORS: true
      DOTENV_PRIVATE_KEY: ${DOTENV_PRIVATE_KEY}
    depends_on:
      cassandra:
        condition: service_healthy
    restart: always

secrets:
  cassandra_secrets:
    file: ./.env

volumes:
  cassandra_data:
