services:
  cassandra:
    environment:
      - CASSANDRA_USER=prod
      - CASSANDRA_PASSWORD=prod
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator

  vpn-backend:
    build:
      context: .
      dockerfile: docker/backend/prod/Dockerfile
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"