name: travelervpn-dev

services:
  cassandra:
    environment:
      CASSANDRA_USER: "dev"
      CASSANDRA_PASSWORD: "dev"
    networks:
      - vpn_network
    ports:
      - "9042:9042"
    restart: always

  vpn-backend:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/backend/dev/Dockerfile
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: sync+restart
          path: ./build.gradle.kts
          target: /app/build.gradle.kts
    restart: always
    networks:
      - vpn_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  vpn_network:
    driver: bridge