spring:
  realityPublicKey: ${realityPublicKey}
  realityShortId: ${realityShortId}
  serverIp: ${serverIp}
  maskDomain: ${maskDomain}
  marzbanUsername: ${marzbanUsername}
  marzbanPassword: ${marzbanPassword}
  xuiToken: ${xuiToken}
  xuiSecretPath: ${xuiSecretPath}
  xuiUsername: ${xuiUsername}
  xuiPassword: ${xuiPassword}

  config:
    import: "vault://"

  cassandra:
    username: ${spring.cassandraUser}
    password: ${spring.cassandraPassword}
    schema-action: recreate-drop-unused

  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: spring
      application-name: "spring"