spring:
  realityPublicKey: ${realityPublicKey}
  realityShortId: ${realityShortId}
  serverIp: ${serverIp}
  maskDomain: ${maskDomain}
  marzbanUsername: ${marzbanUsername}
  marzbanPassword: ${marzbanPassword}
  xuiToken: ${xuiToken}
  xuiSecretPath: ${xuiSecretPath}
  xuiUsername: ${xuiUsername}
  xuiPassword: ${xuiPassword}

  config:
    import: "vault://"

  cassandra:
    username: ${cassandraUser}
    password: ${cassandraPassword}
    schema-action: create_if_not_exists
    keyspace-name: traveler_vpn
    local-datacenter: datacenter1
    contact-points: cassandra:9042

  flyway:
    url: jdbc:cassandra://cassandra:9042/traveler_vpn?localdatacenter=datacenter1
    user: ${cassandraUser}
    password: ${cassandraPassword}
    locations: classpath:cassandra/migration
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    baseline-on-migrate: true
    group: true

  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      fail-fast: true
      kv:
        enabled: true
        backend: secret
        default-context: spring
      application-name: "spring"