maxmind:
  downloadUrls:
    - "https://git.io/GeoLite2-City.mmdb"
    - "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
  dbPath: "./maxmind/GeoLite2-City.mmdb"
  downloadCron: "0 0 1 * * *"

spring:
  marzbanUsername: ${MARZBAN_USERNAME}
  marzbanPassword: ${MARZBAN_PASSWORD}
  xuiToken: ${XUI_TOKEN}
  xuiUsername: ${XUI_USERNAME}
  xuiPassword: ${XUI_PASSWORD}
  xuiAccessUrl: ${XUI_ACCESS_URL}
  xuiSubUrl: ${XUI_SUB_URL}

  cassandra:
    username: ${CASSANDRA_USER}
    password: ${CASSANDRA_PASSWORD}
    schema-action: create_if_not_exists
    keyspace-name: traveler_vpn
    local-datacenter: datacenter1
    contact-points: cassandra:9042

  flyway:
    url: jdbc:cassandra://cassandra:9042/traveler_vpn?localdatacenter=datacenter1
    user: ${CASSANDRA_USER}
    password: ${CASSANDRA_PASSWORD}
    locations: classpath:cassandra/migration
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    baseline-on-migrate: true
    group: true
