---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge Master Panel
  ansible.builtin.import_playbook: "../../ansible/playbooks/master-panel.yml"
- name: Converge Spring Backend
  ansible.builtin.import_playbook: "../../ansible/playbooks/spring-backend.yml"
- name: Converge Node
  ansible.builtin.import_playbook: "../../ansible/playbooks/node.yml"
- name: Converge Add Node Inbound
  ansible.builtin.import_playbook: "../../ansible/playbooks/add-node-inbounds.yml"
