---
- name: Create Infrastructure via Terraform
  hosts: localhost
  gather_facts: false
  vars:
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"

  tasks:
    - name: Apply terraform
      community.general.terraform:
        project_path: "{{ molecule_scenario_directory }}/../../terraform-test"
        state: present
      register: tf_output

    - name: Populate instance config dict
      ansible.builtin.set_fact:
        instance_server:
          instance: "{{ item.key }}"
          address: "{{ item.key }}"
          user: "root"
      with_dict: "{{ tf_output.outputs.instances.value | default({}) }}"
      register: instance_config_dict

    - name: Convert instance config dict to a list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_config_dict.results | default([]) | map(attribute='ansible_facts.instance_server') | list }}"
      when: instance_config_dict.results is defined

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed
          {{ (instance_conf | default([])) | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: instance_config_dict.results is defined
