---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    # no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Destroy terraform
      community.general.terraform:
        project_path: "{{ molecule_scenario_directory }}/../../terraform-test"
        state: absent

    - name: Destroy instance_conf
      ansible.builtin.set_fact:
        instance_conf: []

    - name: Remove molecule instance config file
      ansible.builtin.file:
        path: "{{ molecule_instance_config }}"
        state: absent
