---
serverspace_cities:
  ds1: "🇷🇺 Moscow ⚪"
  ix1: "🇷🇺 Moscow ⚪"
  am2: "🇳🇱 Amsterdam ⚫"
  am2hp: "🇳🇱 Amsterdam 🎮 ⚫"
  nj3: "🇺🇸 New-Jersey ⚫"
  ca: "🇨🇦 Toronto ⚫"
  br: "🇧🇷 San-Paulo ⚫"
  uae: "🇦🇪 Dubai ⚫"
  uz: "🇺🇿 Tashkent"
  kz: "🇰🇿 Almaty"
  kzg3: "🇰🇿 Almaty 🎮"
