"all":
  "children":
    "nodes":
      "hosts":
        "3x-node-0":
          "ansible_connection": "docker"
          "ansible_host": "3x-node-0"
          "inbound_port": 443
          "location": "am2"
    "panels":
      "hosts":
        "3x-ui-0":
          "ansible_connection": "docker"
          "ansible_host": "3x-ui-0"
          "panel_port": 2552
    "spring_backends":
      "hosts":
        "spring-backend-0":
          "ansible_connection": "docker"
          "ansible_host": "spring-backend-0"
