---
- name: Add new inbound connection to master panel
  hosts: spring-backend
  gather_facts: false
  connection: http

  vars:
    local_project_root: "{{ playbook_dir }}/../.."
    local_secrets_file: "{{ local_project_root }}/.secrets"

    xui_url: >-
      {%- if molecule_ephemeral_directory is defined -%}
        http://3x-ui:2552/test
      {%- else -%}
        {{ lookup('ansible.builtin.ini', 'XUI_ACCESS_URL type=properties file=' ~ local_secrets_file) }}
      {%- endif -%}
    xui_api_token: "{{ lookup('ansible.builtin.ini', 'XUI_API_TOKEN type=properties file=' ~ local_secrets_file) }}"

    nodes: "{{ groups['3x-nodes'] }}"

  tasks:
    - name: Test connection to 3x-ui
      ansible.builtin.uri:
        url: "{{ xui_url }}"
        method: GET
        status_code: 200
      register: test_conn
      failed_when: false

    - name: Debug connection info
      ansible.builtin.debug:
        msg: "Connection status: {{ test_conn.status | default('failed') }} URL: {{ xui_url }}"

    - name: Add node to Master-Panel
      ansible.builtin.uri:
        url: "{{ xui_url }}/panel/api/nodes/add"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ xui_api_token }}"
          Content-Type: application/json
        body: "{{ lookup('template', '../templates/node_add_schema.j2') | from_json }}"
      loop: "{{ nodes }}"
      register: node_creation_results

    - name: "Create inbounds for node_id: {{ node_creation_results.obj.id }}"
      ansible.builtin.uri:
        url: "{{ xui_url }}/panel/api/inbounds/add"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ xui_api_token }}"
        body: "{{ lookup('template', '../templates/vless_reality_xhttp.json.j2') | from_json }}"
        status_code: 200
      loop: "{{ node_creation_results.obj }}"
      loop_control:
        label: "{{ item.remark }} ({{ item.transport }})"
