---
- name: Add new inbound connection to master panel
  hosts: spring-backend
  gather_facts: false

  vars:
    local_project_root: "{{ playbook_dir }}/../.."
    local_secrets_file: "{{ local_project_root }}/.secrets"
    xui_url: "{{ lookup('ansible.builtin.ini', 'XUI_ACCESS_URL type=properties file=' ~ local_secrets_file) }}"
    xui_username: "{{ lookup('ansible.builtin.ini', 'XUI_USERNAME type=properties file=' ~ local_secrets_file) }}"
    xui_password: "{{ lookup('ansible.builtin.ini', 'XUI_PASSWORD type=properties file=' ~ local_secrets_file) }}"

  tasks:
    - name: Login to Master-Panel
      ansible.builtin.uri:
        url: "{{ xui_url }}/login"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ xui_username }}"
          password: "{{ xui_password }}"
        status_code: 200
      register: login_response

    - name: Add node to Master-Panel
      ansible.builtin.uri:
        url: "{{ xui_api_url }}/panel/api/nodes/add"
        method: POST
        body_format: form-urlencoded
        headers:
          Cookie: "{{ login_response.set_cookie }}"
        body:
          remark: "{{ item.name }}"
          address: "{{ item.address }}"
          port: "{{ item.port }}"
          apikey: ""
      loop: "{{ nodes }}"
      register: node_creation_results

    - name: "Create inbounds for node_id: {{ node_creation_results.obj.id }}"
      ansible.builtin.uri:
        url: "{{ xui_api_url }}/panel/api/inbounds/add"
        method: POST
        body_format: json
        headers:
          Cookie: "{{ login_response.set_cookie }}"
          Content-Type: "application/json"
        body: "{{ lookup('template', 'templates/vless_reality_xhttp.json.j2') | from_json }}"
        status_code: 200
      loop: "{{ node_creation_results.obj }}"
      loop_control:
        label: "{{ item.remark }} ({{ item.transport }})"
