---
- name: Deploy panel with terraform
  hosts: localhost
  gather_facts: false

  vars:
    local_project_root: "{{ playbook_dir }}/../.."

  tasks:
    - name: Execute terraform
      community.general.terraform:
        project_path: "{{ local_project_root }}/terraform/"
        state: present
        variables:
          node_port: "{{ 65535 | random(start=1024) }}"
          ssh_port: "{{ 65535 | random(start=1024) }}"
          serverspace_token: "{{ serverspace_token }}"
      register: vless_node
      when: molecule_ephemeral_directory is not defined

- name: Install 3x-ui panel and TLS certificate
  hosts: panels
  remote_user: root
  gather_facts: false
  become: true

  vars:
    allowed_keys:
      - XUI_SUB_URL
      - XUI_PANEL_PORT
      - XUI_ACCESS_URL
      - XUI_API_TOKEN
      - XUI_USERNAME
      - XUI_PASSWORD

    local_secrets_file: "{{ playbook_dir }}/../../.env"

  tasks:
    - name: Install pexpect
      ansible.builtin.pip:
        name: pexpect
        state: present

    - name: Check if 3x-ui is already installed
      ansible.builtin.stat:
        path: /usr/bin/install_3x_ui.sh
      register: x_ui_binary

    - name: Download 3x-ui installer script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/MHSanaei/3x-ui/main/install.sh
        dest: /usr/bin/install_3x_ui.sh
        mode: "0755"
      when: not x_ui_binary.stat.exists

    - name: Install 3x-ui
      ansible.builtin.command: install_3x_ui.sh
      environment:
        DEBIAN_FRONTEND: noninteractive
        XUI_NONINTERACTIVE: "1"
        XUI_PANEL_PORT: "{{ xui_port }}"
        XUI_USERNAME: "{{ xui_username }}"
        XUI_PASSWORD: "{{ xui_password }}"
        XUI_SSL_MODE: "none"
      changed_when: true
      when: molecule_ephemeral_directory is not defined

    - name: Install 3x-ui (molecule)
      ansible.builtin.command: install_3x_ui.sh
      environment:
        DEBIAN_FRONTEND: noninteractive
        XUI_NONINTERACTIVE: "1"
        XUI_PANEL_PORT: "{{ xui_port }}"
        XUI_USERNAME: "{{ xui_username }}"
        XUI_PASSWORD: "{{ xui_password }}"
        XUI_WEB_BASE_PATH: "{{ xui_web_base_path }}"
        XUI_SSL_MODE: "none"
      changed_when: true
      when: molecule_ephemeral_directory is defined

    - name: Ensure 3x-ui service is running
      ansible.builtin.systemd:
        name: x-ui
        state: started
        enabled: true
      changed_when: true

    - name: Install tls certificate
      ansible.builtin.expect:
        command: x-ui
        timeout: 60
        responses:
          (?i)selection.*0-28: "20"
          (?i)choose an option: "6"
          (?i)proceed: "y"
          (?i)correct incoming public: "y"
          (?i)ipv6: ""
          (?i)port: "80"
        echo: true

    - name: Check if .env exist
      ansible.builtin.stat:
        path: "{{ local_secrets_file }}"
      register: file_stat
      delegate_to: localhost

    - name: Read .env existing contents
      ansible.builtin.slurp:
        src: "{{ local_secrets_file }}"
      when: file_stat.stat.exists and file_stat.stat.size > 0
      register: existing_secrets_encoded
      delegate_to: localhost
      no_log: true

    - name: Initialize existing_secrets var
      ansible.builtin.set_fact:
        existing_secrets: {}

    - name: If file doesn't exist or empty - create empty object
      ansible.builtin.set_fact:
        existing_secrets: "{{ existing_secrets | combine({ item.split('=', 1)[0] | trim: item.split('=', 1)[1] | trim }) }}"
      loop: "{{ (existing_secrets_encoded['content'] | b64decode | split('\n')) }}"
      when:
        - "existing_secrets_encoded.skipped is not defined"
        - "'=' in item"
      no_log: true

    - name: Read remote 3x-ui credentials
      ansible.builtin.slurp:
        src: /etc/x-ui/install-result.env
      register: remote_file
      no_log: true

    - name: Split up credentials
      ansible.builtin.set_fact:
        remote_lines: "{{ remote_file['content'] | b64decode | split('\n') }}"
      no_log: true

    - name: Initialize creds var
      ansible.builtin.set_fact:
        x_ui_creds: {}

    - name: Set 3x-ui credentials
      ansible.builtin.set_fact:
        x_ui_creds: "{{ x_ui_creds | combine({ item.split('=', 1)[0] | trim: item.split('=', 1)[1] | trim }) }}"
      loop: "{{ remote_lines }}"
      when:
        - "'=' in item"
        - "item.split('=', 1)[0] | trim in allowed_keys"
      no_log: true

    - name: Combine secrets
      ansible.builtin.set_fact:
        final_secrets: "{{ existing_secrets | combine(x_ui_creds) }}"
      no_log: true

    - name: Append secrets to local .env
      ansible.builtin.copy:
        dest: "{{ local_secrets_file }}"
        mode: "0440"
        content: |
          {% for key, value in final_secrets.items() %}
          {{ key }}={{ value }}
          {% endfor %}
      delegate_to: localhost
      no_log: true
