---
- name: Deploy server with terraform
  hosts: localhost
  gather_facts: false

  vars:
    local_project_root: "{{ playbook_dir }}/../.."
    local_secrets_file: "{{ local_project_root }}/.secrets"
    xui_username: "{{ lookup('ansible.builtin.ini', 'XUI_USERNAME type=properties file=' ~ local_secrets_file) }}"
    xui_password: "{{ lookup('ansible.builtin.ini', 'XUI_PASSWORD type=properties file=' ~ local_secrets_file) }}"

  tasks:
    - name: Execute terraform
      community.general.terraform:
        project_path: "{{ local_project_root }}/terraform/"
        state: present
        variables:
          node_port: "{{ 65535 | random(start=1024) }}"
          ssh_port: "{{ 65535 | random(start=1024) }}"
          serverspace_token: "{{ serverspace_token }}"
      register: vless_node
      when: molecule_ephemeral_directory is not defined

- name: Install 3x-ui Node and TLS certificate
  hosts: 3x-nodes
  remote_user: root
  gather_facts: false
  become: true

  tasks:
    - name: Install pexpect
      ansible.builtin.pip:
        name: pexpect
        state: present

    - name: Check if 3x-ui is already installed
      ansible.builtin.stat:
        path: /usr/bin/install_3x_ui.sh
      register: x_ui_binary

    - name: Download 3x-ui installer script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/MHSanaei/3x-ui/main/install.sh
        dest: /usr/bin/install_3x_ui.sh
        mode: "0755"
      when: not x_ui_binary.stat.exists

    - name: Install 3x-ui
      ansible.builtin.command: install_3x_ui.sh
      environment:
        DEBIAN_FRONTEND: noninteractive
        XUI_NONINTERACTIVE: "1"
        XUI_PANEL_PORT: "{{ node_port }}"
        XUI_USERNAME: "{{ xui_username }}"
        XUI_PASSWORD: "{{ xui_password }}"
        XUI_SSL_MODE: "none"
      changed_when: true

    - name: Ensure 3x-ui service is running
      ansible.builtin.systemd:
        name: x-ui
        state: started
        enabled: true
      changed_when: true

    - name: Install tls certificate
      ansible.builtin.expect:
        command: x-ui
        timeout: 60
        responses:
          (?i)selection.*0-28: "20"
          (?i)choose an option: "6"
          (?i)proceed: "y"
          (?i)correct incoming public: "y"
          (?i)ipv6: ""
          (?i)port: "80"
        echo: true

    - name: Read remote 3x-ui credentials
      ansible.builtin.slurp:
        src: /etc/x-ui/install-result.env
      register: remote_file

    - name: Print 3x-ui credentials
      ansible.builtin.debug:
        msg: "{{ remote_file['content'] | b64decode }}"
