---
- name: Deploy server with terraform
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Execute terraform
      community.general.terraform:
        project_path: "{{ local_project_root }}/terraform/"
        state: present
        variables:
          node_port: "{{ 65535 | random(start=1024) }}"
          ssh_port: "{{ 65535 | random(start=1024) }}"
          serverspace_token: "{{ vault_serverspace_token }}"
      register: vless_node
      when: vault_serverspace_token is defined

    - name: Add ip to inventory
      ansible.builtin.add_host:
        name: "spring-backend"
        ansible_host: "{{ vless_node.outputs.public_ip.value }}"
        ansible_user: "root"
      when: vless_node.outputs.public_ip.value is defined

- name: Deploy Spring Backend
  hosts: spring-backend
  remote_user: root
  gather_facts: true
  become: true

  vars:
    local_project_root: "{{ playbook_dir }}/../.."
    remote_project_root: "/opt/travelervpn"
    is_container: >
      {{ ansible_facts['virtualization_type'] | default('') in ['docker', 'containerd']
      or lookup('ansible.builtin.file', '/.dockerenv', errors='ignore') != '' }}

  tasks:
    - name: Full docker install
      when: not is_container
      block:
        - name: Install Docker Script
          ansible.builtin.get_url:
            url: https://get.docker.com/
            dest: /usr/bin/docker_install.sh
            mode: "0755"

        - name: Install Docker
          ansible.builtin.command: docker_install.sh
          changed_when: true

        - name: Ensure Docker service is running and enabled
          ansible.builtin.systemd:
            name: docker
            state: started
            enabled: true

    - name: Install docker cli
      when: is_container
      block:
        - name: Create keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: "0755"

        - name: Download Docker GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: "0444"

        - name: Add Docker repository to apt
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            filename: docker
            state: present
            update_cache: true

        - name: Install docker cli
          ansible.builtin.apt:
            name: docker-ce-cli
            state: present
            update_cache: true

    - name: Create project directory
      ansible.builtin.file:
        path: "{{ remote_project_root }}"
        state: directory
        mode: "0755"
        owner: 100
        group: 1000

    - name: Copy docker directory
      ansible.builtin.copy:
        src: "{{ local_project_root }}/docker/"
        dest: "{{ remote_project_root }}/docker"
        mode: "0740"
        directory_mode: "0750"
        owner: 100
        group: 1000

    - name: Copy .secrets
      ansible.builtin.copy:
        src: "{{ local_project_root }}/.secrets"
        dest: "{{ remote_project_root }}"
        mode: "440"
        owner: 100
        group: 1000
      no_log: true

    - name: Copy main compose
      ansible.builtin.copy:
        src: "{{ local_project_root }}/compose.yaml"
        dest: "{{ remote_project_root }}"
        mode: "440"
        owner: 100
        group: 1000
      no_log: true

    - name: Copy prod compose
      ansible.builtin.copy:
        src: "{{ local_project_root }}/compose.prod.yaml"
        dest: "{{ remote_project_root }}"
        mode: "440"
        owner: 100
        group: 1000
      no_log: true

    - name: Deploy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_root }}"
        files:
          - compose.yaml
          - compose.prod.yaml
        state: present
