---
- name: Provision users and UFW from Host
  hosts: all
  become: true
  gather_facts: false

  vars:
    local_pub_key: "~/.ssh/provisioner.pub"
    local_private_key: "~/.ssh/provisioner.pem"

  tasks:
    - name: Wait for SSH port to become responsive
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 120

    - name: Create deployer user
      ansible.builtin.user:
        name: deployer
        shell: /bin/bash
        state: present
        groups: sudo
        append: true

    - name: Set up authorized_keys directly from host file
      ansible.posix.authorized_key:
        user: deployer
        state: present
        key: "{{ lookup('file', local_pub_key) }}"

    - name: Disable password authentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Disable root login via SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin prohibit-password"
        state: present

    - name: Configure UFW
      ansible.builtin.include_tasks: "../tasks/configure-firewall-ports.yml"
      loop: "{{ groups }}"

    - name: Enable UFW and set default deny
      community.general.ufw:
        state: enabled
        policy: deny
        direction: in
