---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    # no_log: "{{ molecule_no_log }}"

  handlers:
    - name: Generate molecule instance config
      ansible.builtin.include_tasks: handlers/generate_instance.yml

  tasks:
    - name: Create infrastructure instances
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image | default('ubuntu:latest') }}"
        state: started
        command: sleep infinity
      loop: "{{ molecule_yml.platforms }}"
      register: server_jobs
      notify:
        - Generate molecule instance config
