- name: Populate instance config dict # noqa jinja
  ansible.builtin.set_fact:
    server:
      instance: "{{ item.item.name }}"
      address: "127.0.0.1"
      user: "root"
      port: 22
      identity_file: ""
      ansible_connection: community.docker.docker
      ansible_user: root
  with_items: "{{ server_jobs.results }}"
  register: instance_config_dict

- name: Convert instance config dict to a list
  ansible.builtin.set_fact:
    instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.server') | list }}"

- name: Dump instance config
  ansible.builtin.copy:
    content: |
      # Molecule mana
      {{ instance_conf | to_json | from_json | to_yaml }}
    dest: "{{ molecule_instance_config }}"
    mode: "0600"
